# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "所有文章"
  pageRef = "posts"
  weight = 10




[[main]]
  name = "编程"
  pageRef = "programs"
  weight = 20

[[main]]
  name = "Go"
  parent = "编程"
  pageRef = "go"
  weight = 10

[[main]]
  name = "Java"
  parent = "编程"
  pageRef = "java"
  weight = 20

[[main]]
  name = "Web"
  parent = "编程"
  pageRef = "web"
  weight = 30







[[main]]
  name = "摄影"
  pageRef = "photos"
  weight = 30

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 40







[[main]]
  name = "NAS"
  pageRef = "nas"
  weight = 50

[[main]]
  name = "DSM"
  parent = "NAS"
  url = "https://vincent3hsia.top:5001/"
  weight = 10

[[main]]
  name = "Video"
  parent = "NAS"
  url = "https://vincent3hsia.top/video/"
  weight = 20

[[main]]
  name = "Photo"
  parent = "NAS"
  url = "https://vincent3hsia.top/photo/"
  weight = 30





# [[main]]
#   name = "Merch"
#   url = "http://tee.pub/lic/qwSlWVBL5zc"
#   weight = 60

# [[main]]
#   identifier = "twitter"
#   pre = "twitter"
#   url = "https://twitter.com/burufugu"
#   weight = 70

# [[main]]
#   identifier = "mastodon"
#   pre = "mastodon"
#   url = "https://masto.ai/@blowfish"
#   weight = 80

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Vincent3Hsia"
  weight = 100


# [[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#  [[footer]]
#    name = "Tags"
#    pageRef = "tags"
#    weight = 10

#  [[footer]]
#    name = "Authors"
#    pageRef = "authors"
#    weight = 20